config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  # All Routes
  resource :users, except: %i[index update edit], path: "", path_names: {new: :register, show: :profile}
  resource :sessions, only: %i[new create destroy],path: "auth", path_names: {new: :login, destroy: :logout}
  resource :password_resets, except: %i[index show destroy]
  resource :passwords, only: %i[edit update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    normalizes :email, with: -> email {email.strip.downcase}

    validates :email, presence: true, uniqueness: true

    generates_token_for :password_reset, expires_in: 10.minutes do
        #last 10 characters of the password salt
        password_salt&.last(10)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Authentication

    before_action :authenticated!
end

app/controllers/concerns/authentication.rb
module Authentication 
    extend ActiveSupport::Concern

    included do
        helper_method :user_signed_in?, :current_user
    end

    def sign_in(user)
        Current.user = user
        reset_session 
        cookies.encrypted[:user_id] = user.id
    end

    def sign_out(user)
        Current.user = nil
        reset_session
        cookies.delete(:user_id)
    end

    def authenticated!
        if current_user.blank?
            redirect_to new_sessions_path, alert: "You need to sign in to continue"
        end
    end

    def redirect_if_authenticated
        redirect_to root_path if user_signed_in?
    end

    private

    def user_signed_in?
        current_user.present?
    end

    def current_user
        Current.user ||= authenticate_user_from_session
    end

    def authenticate_user_from_session
        User.find_by(id: cookies.encrypted[:user_id])
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticated!
  def index
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    skip_before_action :authenticated!
    before_action :set_user, only: %i[edit update]

    def new
    end

    def create
        if (user = User.find_by(password_reset_params))
            PasswordMailer.with(
                user: user,
                token: user.generate_token_for(:password_reset)
            ).password_reset.deliver_later

        else
            return redirect_to new_password_resets_path, alert: "Email not found."
        end

        redirect_to root_path, notice: "Check your email for a password reset link."
    end

    def edit
    end

    def update
        if @user.update(password_params)
            redirect_to new_sessions_path, notice: "Password updated."
        else
            render :edit, status: :unprocessable_entity
        end
    end

    private

    def password_reset_params
        {email: params[:email]}
    end

    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
    
    def set_user
        @user = User.find_by_token_for(:password_reset, params[:token])
        redirect_to new_password_resets_path, alert: "Invalid or expired token." unless @user.present?
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    def edit
    end

    def update
        if current_user.update(password_params)
            redirect_to root_path, notice: "Password updated."
        else
            render :edit, status: :unprocessable_entity
        end
    end

    private

    def password_params
        params.require(:user).permit(:password, :password_confirmation,:password_challenge).with_defaults(password_challenge: "")
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :authenticated!
    before_action :redirect_if_authenticated, only: %i[new]
    def new
    end

    def create
        if (user = User.authenticate_by(user_params))
            sign_in user
            redirect_to root_path, notice: "Signed in!"
        else
            flash.now[:alert] = "Invalid email or password"
            render "new", status: :unprocessable_entity
        end
    end

    def destroy
        sign_out current_user
        redirect_to new_sessions_path, alert: "Signed out!"
    end

    private
    def user_params
        {email: params[:email], password: params[:password]}
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticated!
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: "Signed up!"
    else
      render "new"
    end
  end
  

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home page</h1>
<%if user_signed_in?%>
    <p> You are authenticated</p>
<%else%>
    <p> Welcome to the homepage</p>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Auth</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="nav">
      <%if user_signed_in?%>
        <%= link_to "Change Password",edit_passwords_path, class: "nav-item"%>
        <%= button_to "Logout",sessions_path,method: :delete, class: "nav-item",data: {turbo_confirm: "Are you sure you want to logout?" }%>
      <%else%>
        <%= link_to "Login",new_sessions_path, class: "nav-item"%>
        <%= link_to "Sign up",new_users_path, class: "nav-item"%>
      <%end%>
    </header>
    <div><%=notice%></div>
    <div><%=alert%></div>
    <%= yield %>
  </body>
</html>

app/views/password_resets/edit.html.erb
<%= form_with model:@user, url: password_resets_path(token: params[:token]), class: "form" do |f| %>
    <div>
        <%=f.label :password%>
        <%= f.password_field :password %>
    <div>
    <div>
        <%=f.label :password_confirmation%>
        <%= f.password_field :password_confirmation %>
    <div>
    <div>
        <%= f.submit "Update Password" %>
    <div>
<%end%>

app/views/password_resets/new.html.erb
<%= form_with url: password_resets_path, class: "form" do |f| %>
    <div>
        <%= f.label :email %>
        <%= f.email_field :email %>
    <div>
    <div>
        <%= f.submit "Reset Password" %>
    <div>
<%end%>

app/views/users/_form.html.erb
<%= form_with model: user do |f|%>
    <%=f.label :email%>
    <%= f.text_field :email %>

    <%=f.label :password%>
    <%= f.password_field :password %>

    <%=f.label :password_confirmation%>
    <%= f.password_field :password_confirmation %>

    <%= f.submit "Sign up" %>
<%end%>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<p> Register </p>

<%= render "form", user: @user %>